highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rex's Blog
tagline:          'Welcome'
description:      Not sure what I will end up writing; but let's see
url:              rexliu.me
baseurl:          /

author:
  name:           'Rex Liu'
  url:            rexliu.me

paginate:         5

# Custom vars
# version:          3.1.3

github:
  repo:           https://github.com/rex911


#gems:
#  - jekyll-paginate
#  - jekyll-gist
#  - pygments.rb
#  - kramdown

